export default function Head() {
  return (
    <>
      <script
        src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_CLIENT_KAKAO_JS_KEY}&autoload=true`}
        async
      />
      <title>쉼표</title>
      <meta name="description" content="Generated by create next app" />
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  );
}
