import './globals.css';

import Header from './(_components)/UI/Header';
import type { Metadata } from 'next';
import TabBar from './(_components)/UI/TabBar';

export const metadata: Metadata = {
  title: '쉼표',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="w-full h-full bg-white">
        <div className="relative flex justify-center items-center min-h-screen">
          <div className="w-[375px] h-screen overflow-hidden relative z-10 flex justify-center items-center">
            <div className="bg-white h-full w-full flex flex-col relative">
              <Header />
              <div className="flex-1 overflow-auto scrollbar-hide">{children}</div>
              <TabBar />
            </div>
          </div>

          <div className="absolute top-0 right-[140px] bottom-0 p-4 z-0 flex justify-center items-center">
            <div className="bg-white p-8 rounded-lg shadow-lg max-w-md">
              <h2 className="text-xl font-bold text-center">Main 문구 들어갈 위치</h2>
              <p className="text-center">description 위치</p>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
