import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '쉼표',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
